### ISSUE TITLE
Setting up an Elixir app with a dependency on khepri does not start

### ISSUE THREAD

**Issue by gordoneliel** [rabbitmq/khepri#214]
### What does not work?

When running an elixir app with khepri as a dependency, app crashes with the following crashlog:

```elixir
[notice] Application khepri exited: exited in: :khepri_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :undefined
            (khepri 0.7.0) src/khepri_utils.erl:258: anonymous fn/3 in :khepri_utils.init_list_of_modules_to_skip/0
            (stdlib 5.0.2) lists.erl:1594: :lists.foldl/3
            (khepri 0.7.0) src/khepri_utils.erl:252: :khepri_utils.init_list_of_modules_to_skip/0
            (khepri 0.7.0) src/khepri_app.erl:26: :khepri_app.start/2
            (kernel 9.0.2) application_master.erl:293: :application_master.start_it_old/4
```

### Expected behavior

It should be able to run with khepri as a dependency

### How to reproduce

Create a mix app, add khepri as a dep, run  with `iex -S mix`

**Comment by gordoneliel** [comment]
Nevermind, got it to work by adding `:mnesia` to the list of `:extra_applications`

**Comment by dumbbell** [comment]
Hi! I think this is a real bug: `khepri_utils` assumes that applications such as `mnesia` and `ssl` are available. This might not be the case in a release for instance. Instead of asserting the return value of `application:get_key/2`, we should handle the case where the application is unavailable.
