### ISSUE TITLE
Prefer to use `erlang:monotonic_time()` to measure a duration

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/khepri#239]
We should use `erlang:monotonic_time()` instead of `erlang:system_time()` to measure a duration in `khepri_machine:do_select_query_type/2`.

Reported by: @ansd

**Comment by lukebakken** [comment]
Related issue, just FYI - https://github.com/rabbitmq/aten/issues/33

**Comment by kjnilsson** [comment]
I think since OTP 26 nmonotinic time in aten may not be necessary as the time warp mode has changed

**Comment by ansd** [comment]
My understanding is the opposite:

> As of Erlang/OTP 26 (ERTS 14.0) the [multi time warp mode](https://www.erlang.org/doc/apps/erts/time_correction#Multi_Time_Warp_Mode) is enabled by default. This assumes that all code executing on the system is [time warp safe](https://www.erlang.org/doc/apps/erts/time_correction#Time_Warp_Safe_Code).

* `assumes that all code executing on the system is time warp safe` means our code must be able to handle wall clock time (i.e. invocations of `erlang:system_time()`) jumping forward and backward.
* therefore, `erlang:system_time(microsecond)` as used in https://github.com/rabbitmq/aten/blob/52720077fc8e366284fdfd4be442bb396bb99935/src/aten_detect.erl#L73 is not time warp safe
* The microsecond digits returned from `erlang:system_time(microsecond)` are meaningless. The return value should be thought of a range of times with some confidence interval (e.g. `+/- 100ms`). The time may jump backward or forward on the next invocation.
* Therefore, we must use monotonic time in aten.
* For all durations measured on a single node, we should use monotonic time.
