### ISSUE TITLE
Export issue using default code in documentation

### ISSUE THREAD

**Issue by sksar** [rabbitmq/khepri#278]
### What does not work?

According to the documentation of import and export, I was trying to export in elixir using the following code:
```
:khepri.export(:config, :khepri_export_erlang, "export.erl")
```
This code is synomonous to the code in the documentation

But this is the error I get after executing this:
```
[debug] Khepri export: calling khepri_export_erlang:abort_write/1:
  opaque data: %{fd: "export.erl"}
[debug] khepri_export_erlang: aborting export to existing file descriptor "export.erl"
```

I am executing this code on my local machine (macbook), in an elixir project.

### Expected behavior

Expected it to export successfully, to the file "export.erl".

### How to reproduce

Install khepri in a elixir / phoenix project.
Use khepri as said in the docs.

**Comment by dumbbell** [comment]
Hi!

Aren’t there other log messages before the ones you put here?

I couldn’t reproduce with Erlang. As I don’t know Elixir, could you please provide the project you used to reproduce, along with the command line to run?

**Comment by sksar** [comment]
> Hi!
> 
> Aren’t there other log messages before the ones you put here?
> 
> I couldn’t reproduce with Erlang. As I don’t know Elixir, could you please provide the project you used to reproduce, along with the command line to run?

I can't really provide the project, as it is propietary code of my comapny. However, this is the full code of the module.

```
defmodule App.Config do
  use GenServer
  def start_link(_), do: GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  @db :config

  @impl true
  def init(_) do
    :khepri.start(".config", @db)
    :khepri.export(@db, :khepri_export_erlang, "export.erl")
    {:ok, %{}}
  end

  def set(key, value) do
    :khepri.put(@db, key, value)
  end

  def get(key) do
    {:ok, data} = :khepri.get(@db, key)
    data
  end
end
```

**Comment by dumbbell** [comment]
Sorry, I didn't mean you should publish the code you are working on, but a small project dedicated to reproduce the problem.

But I think I see the problem: `"export.erl"` is a binary in Elixir, not a string, correct? The code expects a string for the filename. Otherwise, it assumes it's an already opened file descriptor.

I can amke the guard condition more precise so that a binary is also considered a filename.

**Comment by dumbbell** [comment]
Could you please give #279 a try?
