### ISSUE TITLE
{error,ra_leader_unknown}

### ISSUE THREAD

**Issue by Taure** [rabbitmq/khepri#9]
Hi,

I followed the readme and added khepri to rebar.config and .app.src.

Then I did khepri:start().

But I get the error that the ra_leader_unknown. Where can I find how to set it?

**Comment by Taure** [comment]
Solved that you need a named node. so rebar3 shell --sname something  solved it.

**Comment by dumbbell** [comment]
Hi! Sorry, I didn't see your issue... That's a good point. Ra or Khepri should perform a check on startup to ensure Erlang distribution is enabled.

**Comment by lukebakken** [comment]
@Taure I couldn't reproduce this using Erlang `24.1.4`:

```
bakkenl@bakkenl-z01 ~/development/rabbitmq/khepri (main=)
$ rebar3 shell
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling khepri
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Eshell V12.1.4  (abort with ^G)
1> node().
nonode@nohost
2> application:ensure_all_started(khepri).
{ok,[compiler,sasl,aten,gen_batch_server,ra,khepri]}
3>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C
```

**Comment by Taure** [comment]
https://github.com/Taure/stargate

If I run this one with `rebar3 shell` I get it all the time. But I see it is on the insert and not when I start it.
